# YMl file.
---
spring:
  profiles: DEV
book-name: Live Demo Spring Boot 1.x  Microservices
eureka: 
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: QA 
book-name: Spring Boot 2.x  Microservices
eureka: 
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
      
---
spring:
  profiles: PROD 
lucky-word: Minnesota
eureka: 
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
